server:
  port: 8086
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crud_test
    username: crud
    password: crud
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate.SQL: debug