server:
  port: 8086

spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB


  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: demo
    password: demo

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 30
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate.SQL: debug
#      "[org.springframework.security]": DEBUG
#      apache:
#        coyote:
#          http11: debug

file:
  dir: 'C:/upload/'